Ext.define('Cosmo.view.main.maintapbar.mainbody.right.property.RightPropertyControllerData', {
    extend: 'Ext.data.SimpleStore',
    data: {
        hours: [{
            field: ['value', 'text'],
            data: [
                {value: '0', text: '0'}, {value: '1', text: '1'}, {value: '2', text: '2'},
                {value: '3', text: '3'}, {value: '4', text: '4'}, {value: '5', text: '5'},
                {value: '6', text: '6'}, {value: '7', text: '7'}, {value: '8', text: '8'},
                {value: '9', text: '9'}, {value: '10', text: '10'}, {value: '11', text: '11'},
                {value: '12', text: '12'}, {value: '13', text: '13'}, {value: '14', text: '14'},
                {value: '15', text: '15'}, {value: '16', text: '16'}, {value: '17', text: '17'},
                {value: '18', text: '18'}, {value: '19', text: '19'}, {value: '20', text: '20'},
                {value: '21', text: '21'}, {value: '22', text: '22'}, {value: '23', text: '23'},
                {value: '24', text: '24'}, {value: '25', text: '25'}, {value: '26', text: '26'},
                {value: '27', text: '27'}, {value: '28', text: '28'}, {value: '29', text: '29'},
                {value: '30', text: '30'}, {value: '31', text: '31'}, {value: '32', text: '32'},
                {value: '33', text: '33'}, {value: '34', text: '34'}, {value: '35', text: '35'},
                {value: '36', text: '36'}, {value: '37', text: '37'}, {value: '38', text: '38'},
                {value: '39', text: '39'}, {value: '40', text: '40'}, {value: '41', text: '41'},
                {value: '42', text: '42'}, {value: '43', text: '43'}, {value: '44', text: '44'},
                {value: '45', text: '45'}, {value: '46', text: '46'}, {value: '47', text: '47'},
                {value: '48', text: '48'}, {value: '49', text: '49'}, {value: '50', text: '50'},
                {value: '51', text: '51'}, {value: '53', text: '52'}, {value: '53', text: '53'},
                {value: '54', text: '54'}, {value: '55', text: '55'}, {value: '56', text: '56'},
                {value: '57', text: '57'}, {value: '58', text: '58'}, {value: '59', text: '59'}
            ]
        }],
        day: [{
            field: ['value', 'text'],
            data: [
                {value: '0', text: '0'}, {value: '1', text: '1'}, {value: '2', text: '2'},
                {value: '3', text: '3'}, {value: '4', text: '4'}, {value: '5', text: '5'},
                {value: '6', text: '6'}, {value: '7', text: '7'}, {value: '8', text: '8'},
                {value: '9', text: '9'}, {value: '10', text: '10'}, {value: '11', text: '11'},
                {value: '12', text: '12'}, {value: '13', text: '13'}, {value: '14', text: '14'},
                {value: '15', text: '15'}, {value: '16', text: '16'}, {value: '17', text: '17'},
                {value: '18', text: '18'}, {value: '19', text: '19'}, {value: '20', text: '20'},
                {value: '21', text: '21'}, {value: '22', text: '22'}, {value: '23', text: '23'},
            ]
        }],
        week: [{
            field: ['value', 'text'],
            data: [
                {value: '1', text: '星期日'},
                {value: '2', text: '星期一'},
                {value: '3', text: '星期二'},
                {value: '4', text: '星期三'},
                {value: '5', text: '星期四'},
                {value: '6', text: '星期五'},
                {value: '7', text: '星期六'}
            ]
        }],
        month: [{
            field: ['value', 'text'],
            data: [
                {value: '1', text: '1'}, {value: '2', text: '2'},
                {value: '3', text: '3'}, {value: '4', text: '4'}, {value: '5', text: '5'},
                {value: '6', text: '6'}, {value: '7', text: '7'}, {value: '8', text: '8'},
                {value: '9', text: '9'}, {value: '10', text: '10'}, {value: '11', text: '11'},
                {value: '12', text: '12'}, {value: '13', text: '13'}, {value: '14', text: '14'},
                {value: '15', text: '15'}, {value: '16', text: '16'}, {value: '17', text: '17'},
                {value: '18', text: '18'}, {value: '19', text: '19'}, {value: '20', text: '20'},
                {value: '21', text: '21'}, {value: '22', text: '22'}, {value: '23', text: '23'},
                {value: '24', text: '24'}, {value: '25', text: '25'}, {value: '26', text: '26'},
                {value: '27', text: '27'}, {value: '28', text: '28'}, {value: '29', text: '29'},
                {value: '30', text: '30'}, {value: '31', text: '31'}
            ]
        }],
        year: [{
            field: ['value', 'text'],
            data: [
                {value: '1', text: '一月'},
                {value: '2', text: '二月'},
                {value: '3', text: '三月'},
                {value: '4', text: '四月'},
                {value: '5', text: '五月'},
                {value: '6', text: '六月'},
                {value: '7', text: '七月'},
                {value: '8', text: '八月'},
                {value: '9', text: '九月'},
                {value: '10', text: '十月'},
                {value: '11', text: '十一月'},
                {value: '12', text: '十二月'}

            ]
        }],
        timezone: [{
            field: ['value', 'text'],
            data: [
                {ZoneID: 'GMT+0800', text: '中国标准时间'},
                /*{value: 'GMT-11:00', text: '中途岛', ZoneID: 'Pacific/Midway'},
                {value: 'GMT-10:00', text: '檀香山', ZoneID: 'Pacific/Honolulu'},
                {value: 'GMT-08:00', text: '安克雷奇', ZoneID: 'America/Anchorage'},
                {value: 'GMT-07:00', text: '洛杉矶', ZoneID: 'America/Los_Angeles'},
                {value: 'GMT-07:00', text: '蒂华纳', ZoneID: 'America/Tijuana'},
                {value: 'GMT-07:00', text: '凤凰城', ZoneID: 'America/Phoenix'},
                {value: 'GMT-06:00', text: '奇瓦瓦', ZoneID: 'America/Chihuahua'},
                {value: 'GMT-06:00', text: '丹佛', ZoneID: 'America/Denver'},
                {value: 'GMT-06:00', text: '哥斯达黎加', ZoneID: 'America/Costa_Rica'},
                {value: 'GMT-06:00', text: '里贾纳', ZoneID: 'America/Regina'},
                {value: 'GMT-05:00', text: '芝加哥', ZoneID: 'America/Chicago'},
                {value: 'GMT-05:00', text: '墨西哥城', ZoneID: 'America/Mexico_City'},
                {value: 'GMT-05:00', text: '波哥大', ZoneID: 'America/Bogota'},
                {value: 'GMT-04:00', text: '纽约', ZoneID: 'America/New_York'},
                {value: 'GMT-04:00', text: '加拉加斯', ZoneID: 'America/Caracas'},
                {value: 'GMT-04:00', text: '巴巴多斯', ZoneID: 'America/Barbados'},
                {value: 'GMT-04:00', text: '马瑙斯', ZoneID: 'America/Manaus'},
                {value: 'GMT-04:00', text: '圣地亚哥', ZoneID: 'America/Santiago'},
                {value: 'GMT-03:00', text: '哈利法克斯', ZoneID: 'America/Halifax'},
                {value: 'GMT-03:00', text: '累西腓', ZoneID: 'America/Recife'},
                {value: 'GMT-03:00', text: '圣保罗', ZoneID: 'America/Sao_Paulo'},
                {value: 'GMT-03:00', text: '布宜诺斯艾利斯', ZoneID: 'America/Argentina/Buenos_Aires'},
                {value: 'GMT-03:00', text: '蒙得维的亚', ZoneID: 'America/Montevideo'},
                {value: 'GMT-02:30', text: '圣约翰斯', ZoneID: 'America/St_Johns'},
                {value: 'GMT-02:00', text: '戈特霍布', ZoneID: 'America/Godthab'},
                {value: 'GMT-02:00', text: '南乔治亚', ZoneID: 'Atlantic/South_Georgia'},
                {value: 'GMT-01:00', text: '佛得角', ZoneID: 'Atlantic/Cape_Verde'},
                {value: 'GMT+00:00', text: '亚速尔群岛', ZoneID: 'Atlantic/Azores'},
                {value: 'GMT+01:00', text: '卡萨布兰卡', ZoneID: 'Europe/London'},
                {value: 'GMT+01:00', text: '伦敦', ZoneID: 'Africa/Brazzaville'},
                {value: 'GMT+02:00', text: '阿姆斯特丹', ZoneID: 'Europe/Amsterdam'},
                {value: 'GMT+02:00', text: '贝尔格莱德', ZoneID: 'Europe/Belgrade'},
                {value: 'GMT+02:00', text: '布鲁塞尔', ZoneID: 'Europe/Brussels'},
                {value: 'GMT+02:00', text: '马德里', ZoneID: 'Europe/Madrid'},
                {value: 'GMT+02:00', text: '萨拉热窝', ZoneID: 'Europe/Sarajevo'},
                {value: 'GMT+02:00', text: '开罗', ZoneID: 'Africa/Windhoek'},
                {value: 'GMT+02:00', text: '哈拉雷', ZoneID: 'Africa/Harare'},
                {value: 'GMT+03:00', text: '安曼', ZoneID: 'Asia/Amman'},
                {value: 'GMT+03:00', text: '雅典', ZoneID: 'Europe/Athens'},
                {value: 'GMT+03:00', text: '伊斯坦布尔', ZoneID: 'Europe/Istanbul'},
                {value: 'GMT+03:00', text: '贝鲁特', ZoneID: 'Asia/Beirut'},
                {value: 'GMT+03:00', text: '赫尔辛基', ZoneID: 'Europe/Helsinki'},
                {value: 'GMT+03:00', text: '耶路撒冷', ZoneID: 'Asia/Jerusalem'},
                {value: 'GMT+03:00', text: '明斯克', ZoneID: 'Europe/Minsk'},
                {value: 'GMT+03:00', text: '巴格达', ZoneID: 'Asia/Baghdad'},
                {value: 'GMT+03:00', text: '巴格达', ZoneID: 'Asia/Baghdad'},
                {value: 'GMT+03:00', text: '莫斯科', ZoneID: 'Europe/Moscow'},
                {value: 'GMT+03:00', text: '科威特', ZoneID: 'Asia/Kuwait'},
                {value: 'GMT+03:00', text: '内罗毕', ZoneID: 'Africa/Nairobi'},
                {value: 'GMT+04:00', text: '巴库', ZoneID: 'Asia/Baku'},
                {value: 'GMT+04:00', text: '第比利斯', ZoneID: 'Asia/Tbilisi'},
                {value: 'GMT+04:00', text: '埃里温', ZoneID: 'Asia/Yerevan'},
                {value: 'GMT+04:00', text: '迪拜', ZoneID: 'Asia/Dubai'},
                {value: 'GMT+04:00', text: '德黑兰', ZoneID: 'Asia/Tehran'},
                {value: 'GMT+04:00', text: '喀布尔', ZoneID: 'Asia/Kabul'},
                {value: 'GMT+04:00', text: '卡拉奇', ZoneID: 'Asia/Karachi'},
                {value: 'GMT+05:00', text: '乌拉尔', ZoneID: 'Asia/Oral'},
                {value: 'GMT+05:00', text: '叶卡捷琳堡', ZoneID: 'Asia/Yekaterinburg'},
                {value: 'GMT+05:30', text: '加尔各答', ZoneID: 'Asia/Kolkata'},
                {value: 'GMT+05:30', text: '科伦坡', ZoneID: 'Asia/Colombo'},
                {value: 'GMT+05:45', text: '加德满都', ZoneID: 'Asia/Kathmandu'},
                {value: 'GMT+06:00', text: '阿拉木图', ZoneID: 'Asia/Almaty'},
                {value: 'GMT+06:30', text: '仰光', ZoneID: 'Asia/Yangon'},
                {value: 'GMT+07:00', text: '克拉斯诺亚尔斯克', ZoneID: 'Asia/Krasnoyarsk'},
                {value: 'GMT+07:00', text: '曼谷', ZoneID: 'Asia/Bangkok'},
                {value: 'GMT+07:00', text: '雅加达', ZoneID: 'Asia/Jakarta'},
                {value: 'GMT+08:00', text: '中国标准时间', ZoneID: 'Asia/Shanghai'},
                {value: 'GMT+08:00', text: '香港', ZoneID: 'Asia/Hong_Kong'},
                {value: 'GMT+08:00', text: '伊尔库茨克', ZoneID: 'Asia/Irkutsk'},
                {value: 'GMT+08:00', text: '吉隆坡', ZoneID: 'Asia/Kuala_Lumpur'},
                {value: 'GMT+08:00', text: '珀斯', ZoneID: 'Australia/Perth'},
                {value: 'GMT+08:00', text: '台北', ZoneID: 'Asia/Taipei'},
                {value: 'GMT+09:00', text: '首尔', ZoneID: 'Asia/Seoul'},
                {value: 'GMT+09:00', text: '东京', ZoneID: 'Asia/Tokyo'},
                {value: 'GMT+09:30', text: '雅库茨克', ZoneID: 'Asia/Yakutsk'},
                {value: 'GMT+09:30', text: '阿德莱德', ZoneID: 'Australia/Adelaide'},
                {value: 'GMT+09:30', text: '达尔文', ZoneID: 'Australia/Darwin'},
                {value: 'GMT+10:00', text: '布里斯班', ZoneID: 'Australia/Brisbane'},
                {value: 'GMT+10:00', text: '霍巴特', ZoneID: 'Australia/Hobart'},
                {value: 'GMT+10:00', text: '悉尼', ZoneID: 'Australia/Sydney'},
                {value: 'GMT+10:00', text: '符拉迪沃斯托克', ZoneID: 'Asia/Vladivostok'},
                {value: 'GMT+10:00', text: '关岛', ZoneID: 'Pacific/Guam'},
                {value: 'GMT+11:00', text: '马加丹', ZoneID: 'Asia/Magadan'},
                {value: 'GMT+11:00', text: '努美阿', ZoneID: 'Pacific/Noumea'},
                {value: 'GMT+12:00', text: '马朱罗', ZoneID: 'Pacific/Majuro'},
                {value: 'GMT+12:00', text: '奥克兰', ZoneID: 'Pacific/Auckland'},
                {value: 'GMT+12:00', text: '斐济', ZoneID: 'Pacific/Fiji'},
                {value: 'GMT+13:00', text: '东加塔布', ZoneID: 'Pacific/Tongatapu'}*/
            ]
        }]
    }
})