Ext.define('Cosmo.util.Tpl',{

    singleton:true,

    alternateClassName:['Cosmo.Tpl','Tpl'],

    /** 样式空白页面 */
    STYLE_DEFAULT:
        new Ext.XTemplate(
            '<div class="pageBoxCont">',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">页面排列</span>',
                    '<div class="fr pubRight">',
                        '<ul class="alignMent alignMentAlign fr" style="margin-right:8px;padding-left:0;width:66px;position:relative;">',
                            '<div class="styleShadow fontStyleIcon pageAlignLeft pubClickBg" title="左侧对齐">',
                                '<span class="iconStyle  style_AlignLeft small-Style"></span>',
                            '</div>',
                            '<div class="styleShadow fontStyleIcon pageAlignCenter" title="水平居中" style="border-top-right-radius:2px !important;border-bottom-right-radius:2px !important;">',
                                '<span class="iconStyle style_AlignCenter small-Style"></span>',
                            '</div>',
                        '</ul>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">背景颜色</span>',
                    '<div class="fr pubRight">',
                        '<div class="styleShadow pageFillColor fl" style="margin-right:5px;position:relative;width:44px;height:22px;border:none;" title="填充颜色">',
                            '<input type="text" class="pageFill_color" style="display:none;">',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">背景图片</span>',
                    '<div class="fr pubRight">',
                        '<div class="fl" style="margin-bottom:5px;">',
                            '<div class="imgBox styleShadow fl" style="height: 44px;"></div>',
                            '<div class="importImg styleShadow fl">导入</div>',
                            '<div class="emptyImg styleShadow fl">清空</div>',
                        '</div>',
                        '<div class="fl" style="margin-bottom: 5px;">',
                            '<ul class="alignMent alignMentAlign fr" style="margin-right:8px;padding-left:0;width:66px;position:relative;">',
                                '<div class="styleShadow fontStyleIcon pageAlignLeft" title="左侧对齐">',
                                    '<div class="border">',
                                        '<span class="imgPosition"></span>',
                                    '</div>',
                                '</div>',
                                '<div class="styleShadow fontStyleIcon pageAlignCenter" title="水平居中">',
                                    '<div class="border">',
                                        '<span class="imgPosition" style="left:3px;"></span>',
                                    '</div>',
                                '</div>',
                                '<div class="styleShadow fontStyleIcon pageAlignRight" title="右侧对齐">',
                                    '<div class="border">',
                                        '<span class="imgPosition" style="left:6px;"></span>',
                                    '</div>',
                                '</div>',
                            '</ul>',

                            '<ul class="alignMent alignVertical fr" style="margin:0;width:66px;">',
                                '<div class="styleShadow fontStyleIcon pageAlignTop" title="顶部对齐">',
                                    '<div class="border">',
                                        '<span class="imgPosition" style="top:-3px;left:3px;"></span>',
                                    '</div>',
                                '</div>',
                                '<div class="styleShadow fontStyleIcon pageVerticalCenter" title="垂直居中">',
                                    '<div class="border">',
                                        '<span class="imgPosition" style="left:3px;"></span>',
                                    '</div>',
                                '</div>',
                                '<div class="styleShadow fontStyleIcon pageAlignBottom" title="底部对齐">',
                                    '<div class="border">',
                                        '<span class="imgPosition" style="top:3px;left:3px;"></span>',
                                    '</div>',
                                '</div>',
                            '</ul>',
                        '</div>',

                        '<select class="fl imgRepeat" title="Repeat Background Image" style="background-color: #e3e7e9;border:1px solid #e3e7e9;width:142px !important;">',
                            '<option value="0">不重复</option>',
                            '<option value="1">重复图片</option>',
                            '<option value="2">水平重复</option>',
                            '<option value="3">垂直重复</option>',
                            '<option value="4">填充</option>',
                            '<option value="5">适应</option>',
                        '</select>',
                    '</div>',
                '</div>',
            '</div>'
        ),

    /** 样式头部 */
    STYLE_HEADER:
     new Ext.XTemplate(
         '<ul class="boxCont" id="{id}">',
            '<li>',
                '<span class="fl pubLeft">引用样式</span>',
                '<div class="fr pubRight">',
                    '<input type="text" value="" class="quoteStyleVal" disabled="disabled">',
                    '<div class="quoteStyleBtn">...</div>',
                    '<div class="x-fa fa-trash clearQuoseStyle" title="清除引用样式"></div>',
                '</div>',
            '</li>',
            '<li>',
                '<span class="fl pubLeft">位置</span>',
                '<div class="fr pubRight">',
                    '<div class="rLeft fl">',
                        '<tpl if="eleLeft==\'false\'">',
                            '<input type="text" class="eleLeft" disabled style="background-color: #737373;">',
                        '<tpl else>',
                            '<input type="text" class="eleLeft">',
                        '</tpl>',
                        '<span class="spanText">X</span>',
                    '</div>',
                    '<div class="rLeft fr">',
                        '<tpl if="eleTop==\'false\'">',
                            '<input type="text" class="eleTop" disabled style="background-color: #737373;">',
                        '<tpl else>',
                            '<input type="text" class="eleTop">',
                        '</tpl>',
                        '<span class="spanText">Y</span>',
                    '</div>',
                '</div>',
            '</li>',
            '<li>',
                '<span class="fl pubLeft">尺寸</span>',
                '<div class="fr pubRight">',
                    '<div class="rLeft fl">',
                         '<tpl if="eleWidth==\'false\'">',
                            '<input type="text" class="eleWidth" disabled style="background-color: #737373;">',
                         '<tpl else>',
                            '<input type="text" class="eleWidth"><br>',
                         '</tpl>',
                        '<span class="spanText">宽</span>',
                    '</div>',
                    '<div class="rLeft fr">',
                         '<tpl if="eleHeight==\'false\'">',
                            '<input type="text" class="eleHeight" disabled style="background-color: #737373;">',
                         '<tpl else>',
                            '<input type="text" class="eleHeight"><br>',
                         '</tpl>',
                        '<span class="spanText">高</span>',
                    '</div>',
                '</div>',
            '</li>',
            '<li>',
                '<span class="fl pubLeft">角度</span>',
                '<div class="fr pubRight">',
                    '<div class="rLeft fl">',
                         '<tpl if="eleRotation==\'false\'">',
                            '<input type="text" value="0" class="eleRotation" disabled style="background-color: #737373;">',
                         '<tpl else>',
                            '<input type="text" value="0" class="eleRotation">',
                         '</tpl>',
                        '<span class="spanText">元件</span>',
                    '</div>',
                    '<div class="rLeft fr">',
                         '<tpl if="textRotation==\'false\'">',
                            '<input type="text" value="0" class="textRotation" disabled style="background-color: #737373;">',
                         '<tpl else>',
                            '<input type="text" value="0" class="textRotation">',
                         '</tpl>',
                        '<span class="spanText">文本</span>',
                    '</div>',
                '</div>',
            '</li>',
            '<li style="padding: 0 20px 0 30px;">',
                '<tpl if="flipHorizontal==\'false\'">',
                    '<div class="styleShadow fontStyleIcon fl" title="水平翻转" id="flipHorizontal" style="border:none;">',
                        '<span class="iconStyle small-Style style_Level" style="margin: 3px 3px 0 0px !important;"></span>',
                        '<div class="styleMask"></div>',
                    '</div>',
                '<tpl else>',
                    '<div class="styleShadow fontStyleIcon fl" title="水平翻转" id="flipHorizontal">',
                        '<span class="iconStyle small-Style style_Level" style="margin:3px 3px 0 0px !important;"></span>',
                    '</div>',
                '</tpl>',

                '<tpl if="flipVertical==\'false\'">',
                    '<div class="styleShadow fontStyleIcon fl ml2" title="垂直翻转" id="flipVertical" style="border:none;">',
                        '<span class="iconStyle small-Style style_Vertical" style="margin:3px 3px 0 0px !important;"></span>',
                        '<div class="styleMask"></div>',
                    '</div>',
                '<tpl else>',
                    '<div class="styleShadow fontStyleIcon fl ml2" title="垂直翻转" id="flipVertical">',
                        '<span class="iconStyle small-Style style_Vertical" style="margin:3px 3px 0 0px !important;"></span>',
                    '</div>',
                '</tpl>',

                '<tpl if="fitTextWidth==\'false\'">',
                    '<div class="styleShadow fontStyleIcon fl" title="自动适应文本宽度" style="border:none;">',
                        '<span class="iconStyle small-Style style_TextWidth" style="margin: 3px 3px 0 0px !important;"></span>',
                        '<div class="styleMask"></div>',
                    '</div>',
                '<tpl else>',
                    '<div class="styleShadow fontStyleIcon fl" title="自动适应文本宽度">',
                        '<span class="iconStyle small-Style style_TextWidth" style="margin: 3px 3px 0 0px !important;"></span>',
                    '</div>',
                '</tpl>',

                '<tpl if="fitTextHeight==\'false\'">',
                    '<div class="styleShadow fontStyleIcon fl" title="自动适应文本高度" style="margin:0;border: none;">',
                        '<span class="iconStyle small-Style style_TextHeight" style="margin:3px 3px 0 0px !important;"></span>',
                        '<div class="styleMask"></div>',
                    '</div>',
                '<tpl else>',
                    '<div class="styleShadow fontStyleIcon fl" title="自动适应文本高度" style="margin: 0">',
                        '<span class="iconStyle small-Style style_TextHeight" style="margin:3px 3px 0 0px !important;"></span>',
                    '</div>',
                '</tpl>',

            '</li>',
         '</ul>'
     )
,
/** 样式Tab页*/
STYLE_BODY:
     new Ext.XTemplate(
        '<div class="boxCont" id="{id}">',
        '<tpl for="styles">',
            '<tpl if="id==\'fill\' && display==\'true\'">',
                '<div class="styleLine" title="填充颜色">',
                    '<span class="fl pubLeft">填充</span>',
                    '<tpl for="children">',
                        '<tpl if="id==\'fillColor\' && fillColor==\'false\'">',
                             '<div class="fr pubRight">',
                                '<div class="styleShadow fillColor fl" style="margin-right:5px;position:relative;width:44px;height:22px;border:none;" css="{renterTo}" title="填充颜色">',
                                    '<input css="{renterTo}" disabled type="text" class="color_b fill_color fl" readonly="" style="display:none;">',
                                    '<div class="styleMask"></div>',
                                '</div>',
                             '</div>',
                        '<tpl else>',
                             '<div class="fr pubRight">',
                                '<div class="styleShadow fillColor fl" style="margin-right:5px;position:relative;width:44px;height:22px;border:none;" css="{renterTo}" title="填充颜色">',
                                    '<input css="{renterTo}" type="text" class="color_b fill_color fl" readonly="" style="display:none;">',
                                '</div>',
                             '</div>',
                        '</tpl>',
                    '</tpl>',
                '</div>',
            '</tpl>',

            '<tpl if="id==\'shadow\' && display==\'true\'">',
                '<div class="styleLine">',
                    '<span class="fl pubLeft">阴影</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                            '<tpl switch="id">',
                                '<tpl case="outerShadow">',
                                    '<tpl if="id==\'outerShadow\' && outerShadow==\'false\'">',
                                        '<div class="styleShadow shadowOuter fl" title="外部阴影" css="{renterTo}" style="margin-right:5px;border:none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_OuterShadow"></span>',
                                            '<div class="shadowInner pubHideBox" style="height:100px;">',
                                                '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetOuterX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetOuterY" css="{renterTo}" disabled></div>',
                                                '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurOuter" css="{renterTo}" disabled> 颜色 <div class="outerShadow"><div class="styleMask"></div><input class="color_b colorOuter" css="{renterTo}" readonly style="display:none;"></div></div>',
                                             '</div>',
                                             '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow shadowOuter fl" title="外部阴影" css="{renterTo}" style="margin-right:5px;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_OuterShadow"></span>',
                                            '<div class="shadowInner pubHideBox" style="height:100px;">',
                                                '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetOuterX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetOuterY" css="{renterTo}" disabled></div>',
                                                '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurOuter" css="{renterTo}" disabled> 颜色 <div class="outerShadow"><input class="color_b colorOuter" css="{renterTo}" readonly style="display:none;"><div class="styleMask" style="display: block;"></div></div></div>',
                                            '</div>',
                                        '</div>',
                                    '</tpl>',
                                '<tpl case="innerShadow">',
                                    '<tpl if="id==\'innerShadow\' && innerShadow==\'false\'">',
                                        '<div class="styleShadow shadowBox fl" css="{renterTo}" title="内部阴影" style="border:none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_InnerShadow"></span>',
                                            '<div class="shadowInner pubHideBox" style="right:-50px !important;">',
                                                '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetInnerX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetInnerY" css="{renterTo}" disabled></div>',
                                                '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurInner" css="{renterTo}" disabled> 颜色 <div class="innerShadow"><input class="color_b colorInner" css="{renterTo}" readonly style="display:none;"><div class="styleMask" style="display: block;"></div></div></div>',
                                                '<div class="shadowMaskFather">阴影尺寸: <input type="text" class="readonlyIput spreadInner" css="{renterTo}" disabled></div>',
                                            '</div>',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow shadowBox fl" css="{renterTo}" title="内部阴影">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_InnerShadow"></span>',
                                            '<div class="shadowInner pubHideBox" style="right:-50px !important;">',
                                                '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetInnerX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetInnerY" css="{renterTo}" disabled></div>',
                                                '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurInner" css="{renterTo}" disabled> 颜色 <div class="innerShadow"><input class="color_b colorInner" css="{renterTo}" readonly style="display:none;"><div class="styleMask" style="display: block;"></div></div></div>',
                                                '<div class="shadowMaskFather">阴影尺寸: <input type="text" class="readonlyIput spreadInner" css="{renterTo}" disabled></div>',
                                            '</div>',
                                        '</div>',
                                    '</tpl>',
                            '</tpl>',
                        '</tpl>',
                    '</div>',
                '</div>',
            '</tpl>',
            '<tpl if="id==\'border\' && display==\'true\'">',
                '<div class="styleLine">',
                    '<span class="fl pubLeft">边框</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                            '<tpl switch="id">',
                                '<tpl case="linPattern">',
                                    '<tpl if="id==\'linPattern\' && linPattern==\'false\'">',
                                        '<div class="styleShadow borderBox fl" css="{renterTo}" title="线段类型" style="border:none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_Rem"></span>',
                                            '<ul class="pubBox borderInner pubHideBox">',
                                                '<li name="none" class="" style="color:#ccc;text-align: center;">',
                                                    'None',
                                                '</li>',
                                                '<li class="line_01" name="dotted">',
                                                    '<div style="border-bottom:1px dotted #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_02" name="dashed">',
                                                    '<div style="border-bottom:1px dashed #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_03" name="solid">',
                                                    '<div style="border-bottom:1px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="double">',
                                                    '<div style="border-bottom:3px double #ccc;height: 15px;"></div>',
                                                '</li>',
                                            '</ul>',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow borderBox fl" css="{renterTo}" title="线段类型">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_Rem"></span>',
                                            '<ul class="pubBox borderInner pubHideBox">',
                                                '<li name="none" class="" style="color:#ccc;text-align: center;">',
                                                    'None',
                                                '</li>',
                                                '<li class="line_01" name="dotted">',
                                                    '<div style="border-bottom:1px dotted #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_02" name="dashed">',
                                                    '<div style="border-bottom:1px dashed #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_03" name="solid">',
                                                    '<div style="border-bottom:1px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="double">',
                                                    '<div style="border-bottom:3px double #ccc;height: 15px;"></div>',
                                                '</li>',
                                            '</ul>',
                                        '</div>',
                                    '</tpl>',

                                '<tpl case="lineColor">',
                                    '<tpl if="id==\'lineColor\' && lineColor==\'false\'">',
                                        '<div class="styleShadow borderColor fl" style="margin-right:5px;position:relative;width:44px;height:22px;border:none;" css="{renterTo}" title="边框颜色">',
                                            '<input class="border_color" title="线条颜色" style="display:none;">',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow borderColor fl" style="margin-right:5px;position:relative;width:44px;height:22px;border:none;" css="{renterTo}" title="边框颜色">',
                                            '<input class="border_color" title="线条颜色" style="display:none;">',
                                        '</div>',
                                    '</tpl>',
                                '<tpl case="lineWidth">',
                                    '<tpl if="id==\'lineWidth\' && lineWidth==\'false\'">',
                                        '<div class="styleShadow borderWidthBox fl" id="" css="{renterTo}" title="边框宽度" style="margin-right:5px;border:none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_LineWidth"></span>',
                                            '<ul class="pubBox borderWidthInner pubHideBox" style="right:-80px;>',
                                                '<li name="0" class=""></li>',
                                                '<li name="0" class="">',
                                                    '<div style="border-bottom:0px solid #ccc;height: 15px;color:#ccc;text-align: center;">None</div>',
                                                '</li>',
                                                '<li class="line_01" name="1px">',
                                                    '<div style="border-bottom:1px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_02" name="2px">',
                                                    '<div style="border-bottom:2px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_03" name="3px">',
                                                    '<div style="border-bottom:3px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="4px">',
                                                    '<div style="border-bottom:4px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="5px">',
                                                    '<div style="border-bottom:5px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                            '</ul>',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow borderWidthBox fl" id="" css="{renterTo}" title="边框宽度" style="margin-right: 5px;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_LineWidth"></span>',
                                            '<ul class="pubBox borderWidthInner pubHideBox" style="right:-80px;>',
                                                '<li name="0" class=""></li>',
                                                '<li name="0" class="">',
                                                    '<div style="border-bottom:0px solid #ccc;height: 15px;color: #ccc;text-align: center;">None</div>',
                                                '</li>',
                                                '<li class="line_01" name="1px">',
                                                    '<div style="border-bottom:1px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_02" name="2px">',
                                                    '<div style="border-bottom:2px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_03" name="3px">',
                                                    '<div style="border-bottom:3px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="4px">',
                                                    '<div style="border-bottom:4px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                                '<li class="line_04" name="5px">',
                                                    '<div style="border-bottom:5px solid #ccc;height: 15px;"></div>',
                                                '</li>',
                                            '</ul>',
                                        '</div>',
                                    '</tpl>',
                                '</tpl>',
                    '</tpl>',
                    '<div style="margin-top:10px;float:left;width: 100%;">',
                        '<tpl for="children">',
                            '<tpl switch="id">',
                                '<tpl case="arrowStyle">',
                                    '<tpl if="arrowStyle==\'false\'">',
                                        '<div class="styleShadow fl" css="{renterTo}" id="{parent.id}_arrowStyle" title="箭头样式" style="border:none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_Arrow"></span>',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow fl" css="{renterTo}" id="{parent.id}_arrowStyle" title="箭头样式">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_Arrow"></span>',
                                        '</div>',
                                    '</tpl>',
                                '<tpl case="lineVisibility">',
                                    '<tpl if="id==\'lineVisibility\' && lineVisibility==\'false\'">',
                                        '<div class="styleShadow borderHideBox fl" title="边框可见性" style="margin-right:5px;border: none;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_LineVisibility"></span>',
                                            '<div class="pubBox borderHide pubHideBox" css="{renterTo}" style="display:none;right:-53px;">',
                                                '<div class="pubBorRsDiv borderDiv">',
                                                    '<div class="borderDivPub borderDivTop" name="none"></div>',
                                                    '<div class="borderDivPub borderDivBottom" name="none"></div>',
                                                    '<div class="borderDivPub borderDivLeft" name="none"></div>',
                                                    '<div class="borderDivPub borderDivRight" name="none"></div>',
                                                '</div>',
                                            '</div>',
                                            '<div class="styleMask"></div>',
                                        '</div>',
                                    '<tpl else>',
                                        '<div class="styleShadow borderHideBox fl" title="边框可见性" style="margin-right:5px;">',
                                            '<span class="icon2"></span>',
                                            '<span class="iconStyle style_LineVisibility"></span>',
                                            '<div class="pubBox borderHide pubHideBox" css="{renterTo}" style="display:none;right:-53px;">',
                                                '<div class="pubBorRsDiv borderDiv">',
                                                    '<div class="borderDivPub borderDivTop" name="none"></div>',
                                                    '<div class="borderDivPub borderDivBottom" name="none"></div>',
                                                    '<div class="borderDivPub borderDivLeft" name="none"></div>',
                                                    '<div class="borderDivPub borderDivRight" name="none"></div>',
                                                '</div>',
                                            '</div>',
                                        '</div>',
                                    '</tpl>',
                            '<tpl default>',
                            '',
                            '</tpl>',
                        '</tpl>',
                    '</div>',
                '</div>',
                '</div>',
            '</tpl>',

            '<tpl if="id==\'radius\' && display==\'true\'">',
                '<div class="styleLine">',
                '<span class="fl pubLeft">圆角半径</span>',
                '<div class="fr pubRight">',
                    '<tpl for="children">',
                        '<tpl if="id==\'setRadius\' && setRadius==\'false\'">',
                            '<input type="text" value="0" class="setRadius" css="{renterTo}" style="float:left;width:44px;height:22px;margin-right:5px;background-color: #7B7C7D;" disabled>',
                            '<div class="styleShadow styleRadius fl" style="border:none;">',
                                '<span class="icon2"></span>',
                                '<span class="iconStyle style_Radius"></span>',
                                '<div class="pubBox radiusHide pubHideBox" css="{renterTo}" style="display:none;">',
                                    '<div class="radiusDiv" style="border-radius: 26px;width:40px;height:40px;border: 2px solid #777777;display:table-cell;vertical-align:middle;background-color: #fff;position: relative;">',
                                        '<div class="borderDivPub radiusDivTop"></div>',
                                        '<div class="borderDivPub radiusDivBottom"></div>',
                                        '<div class="borderDivPub radiusDivLeft"></div>',
                                        '<div class="borderDivPub radiusDivRight"></div>',
                                    '</div>',
                                '</div>',
                                '<div class="styleMask"></div>',
                            '</div>',
                        '<tpl else>',
                            '<input type="text" value="0" class="setRadius" css="{renterTo}" style="float:left;width:44px;height:22px;margin-right:5px;">',
                            '<div class="styleShadow styleRadius fl">',
                                '<span class="icon2"></span>',
                                '<span class="iconStyle style_Radius"></span>',
                                '<div class="pubBox radiusHide pubHideBox" css="{renterTo}" style="display:none;">',
                                    '<div class="radiusDiv" style="border-radius: 26px;width:40px;height:40px;border: 2px solid #777777;display:table-cell;vertical-align:middle;background-color: #fff;position: relative;">',
                                        '<div class="borderDivPub radiusDivTop"></div>',
                                        '<div class="borderDivPub radiusDivBottom"></div>',
                                        '<div class="borderDivPub radiusDivLeft"></div>',
                                        '<div class="borderDivPub radiusDivRight"></div>',
                                    '</div>',
                                '</div>',
                            '</div>',
                        '</tpl>',
                    '</tpl>',
                '</div>',
                '</div>',
            '</tpl>',

            '<tpl if="id==\'opacity\' && display==\'true\'">',
                '<div class="styleLine">',
                    '<span class="fl pubLeft">不透明</span>',
                    '<div class="fr pubRight">',
                            '<tpl for="children">',
                                '<tpl if="id==\'opacityValue\' && opacityValue==\'false\'">',
                                    '<input css="{renterTo}" id="{parent.id}_opacityValue" class="setOpcity" disabled type="text" value="100" style="float:left;width:44px;height:22px;background-color: #7B7C7D;">',
                                '<tpl else>',
                                    '<input css="{renterTo}" id="{parent.id}_opacityValue" class="setOpcity" type="text" value="100" style="float:left;width:44px;height:22px;">',
                            '</tpl>',
                        '</tpl>',
                        '<span class="fl" style="line-height:22px;">%</span>',
                    '</div>',
                '</div>',
            '</tpl>',

             '<tpl if="id==\'font\' && display==\'true\'">',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">字体</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                            '<tpl switch="id">',
                                '<tpl case="fontFamily">',
                                    '<tpl if="fontFamily==\'false\'">',
                                         '<select name="" id="" class="styleSelect fl" css="{renterTo}" disabled title="字体系列" style="background-color: #7B7C7D;color: #BABABA;border:none;">',
                                             '<option value="仿宋_GB2312">仿宋</option>',
                                             '<option value="华文中宋">华文中宋</option>',
                                             '<option value="华文仿宋">华文仿宋</option>',
                                             '<option value="华文宋体">华文宋体</option>',
                                             '<option value="华文彩云">华文彩云</option>',
                                             '<option value="华文新魏">华文新魏</option>',
                                             '<option value="华文楷体">华文楷体</option>',
                                             '<option value="华文琥珀">华文琥珀</option>',
                                             '<option value="华文细黑">华文细黑</option>',
                                             '<option value="华文行楷">华文行楷</option>',
                                             '<option value="华文隶书">华文隶书</option>',
                                             '<option value="宋体">宋体</option>',
                                             '<option value="宋体-PUA">宋体-PUA</option>',
                                             '<option value="宋体-方正超大字符集">宋体-方正超大字符集</option>',
                                             '<option value="幼圆">幼圆</option>',
                                             '<option value="微软雅黑">微软雅黑</option>',
                                             '<option value="新宋体">新宋体</option>',
                                             '<option value="方正姚体">方正姚体</option>',
                                             '<option value="方正舒体">方正舒体</option>',
                                             '<option value="楷体_GB2312">楷体_GB2312</option>',
                                             '<option value="隶书">隶书</option>',
                                             '<option value="黑体">黑体</option>',
                                             '<option value="Agency FB">Agency FB</option>',
                                             '<option value="Algerian">Algerian</option>',
                                             '<option value="Arial">Arial</option>',
                                             '<option value="Arial Black">Arial Black</option>',
                                             '<option value="Arial Narrow">Arial Narrow</option>',
                                             '<option value="Arial Rounded MT Bold">Arial Rounded MT Bold</option>',
                                             '<option value="Arial Unicode MS">Arial Unicode MS</option>',
                                             '<option value="Baskerville Old Face">Baskerville Old Face</option>',
                                             '<option value="Batang">Batang</option>',
                                             '<option value="BatangChe">BatangChe</option>',
                                             '<option value="Bauhaus 93">Bauhaus 93</option>',
                                             '<option value="Bell MT">Bell MT</option>',
                                             '<option value="Berlin Sans FB">Berlin Sans FB</option>',
                                             '<option value="Berlin Sans FB Demi">Berlin Sans FB Demi</option>',
                                             '<option value="Bernard MT Condensed">Bernard MT Condensed</option>',
                                             '<option value="Blackadder ITC">Blackadder ITC</option>',
                                             '<option value="Bodoni MT">Bodoni MT</option>',
                                             '<option value="Bodoni MT Black">Bodoni MT Black</option>',
                                             '<option value="Bodoni MT Condensed">Bodoni MT Condensed</option>',
                                             '<option value="Bodoni MT Poster Compressed">Bodoni MT Poster Compressed</option>',
                                             '<option value="Book Antiqua">Book Antiqua</option>',
                                             '<option value="Bookman Old Style">Bookman Old Style</option>',
                                             '<option value="Bookshelf Symbol 7">Bookshelf Symbol 7</option>',
                                             '<option value="Bradley Hand ITC">Bradley Hand ITC</option>',
                                             '<option value="Britannic Bold">Britannic Bold</option>',
                                             '<option value="Broadway">Broadway</option>',
                                             '<option value="Brush Script MT">Brush Script MT</option>',
                                             '<option value="Calibri">Calibri</option>',
                                             '<option value="Californian FB">Californian FB</option>',
                                             '<option value="Calisto MT">Calisto MT</option>',
                                             '<option value="Cambria">Cambria</option>',
                                             '<option value="Cambria Math">Cambria Math</option>',
                                             '<option value="Candara">Candara</option>',
                                             '<option value="Castellar">Castellar</option>',
                                             '<option value="Centaur">Centaur</option>',
                                             '<option value="Century">Century</option>',
                                             '<option value="Century Gothic">Century Gothic</option>',
                                             '<option value="Century Schoolbook">Century Schoolbook</option>',
                                             '<option value="Chiller">Chiller</option>',
                                             '<option value="Colonna MT">Colonna MT</option>',
                                             '<option value="Comic Sans MS">Comic Sans MS</option>',
                                             '<option value="Consolas">Consolas</option>',
                                             '<option value="Constantia">Constantia</option>',
                                             '<option value="Cooper Black">Cooper Black</option>',
                                             '<option value="Copperplate Gothic Bold">Copperplate Gothic Bold</option>',
                                             '<option value="Copperplate Gothic Light">Copperplate Gothic Light</option>',
                                             '<option value="Corbel">Corbel</option>',
                                             '<option value="Courier New">Courier New</option>',
                                             '<option value="Curlz MT">Curlz MT</option>',
                                         '</select>',
                                    '<tpl else>',
                                         '<select name="" id="" class="styleSelect fl" css="{renterTo}" title="字体系列" style="background-color: #e3e7e9;border:1px solid #e3e7e9">',
                                             '<option value="仿宋_GB2312">仿宋</option>',
                                             '<option value="华文中宋">华文中宋</option>',
                                             '<option value="华文仿宋">华文仿宋</option>',
                                             '<option value="华文宋体">华文宋体</option>',
                                             '<option value="华文彩云">华文彩云</option>',
                                             '<option value="华文新魏">华文新魏</option>',
                                             '<option value="华文楷体">华文楷体</option>',
                                             '<option value="华文琥珀">华文琥珀</option>',
                                             '<option value="华文细黑">华文细黑</option>',
                                             '<option value="华文行楷">华文行楷</option>',
                                             '<option value="华文隶书">华文隶书</option>',
                                             '<option value="宋体">宋体</option>',
                                             '<option value="宋体-PUA">宋体-PUA</option>',
                                             '<option value="宋体-方正超大字符集">宋体-方正超大字符集</option>',
                                             '<option value="幼圆">幼圆</option>',
                                             '<option value="微软雅黑">微软雅黑</option>',
                                             '<option value="新宋体">新宋体</option>',
                                             '<option value="方正姚体">方正姚体</option>',
                                             '<option value="方正舒体">方正舒体</option>',
                                             '<option value="楷体_GB2312">楷体_GB2312</option>',
                                             '<option value="隶书">隶书</option>',
                                             '<option value="黑体">黑体</option>',
                                             '<option value="Agency FB">Agency FB</option>',
                                             '<option value="Algerian">Algerian</option>',
                                             '<option value="Arial">Arial</option>',
                                             '<option value="Arial Black">Arial Black</option>',
                                             '<option value="Arial Narrow">Arial Narrow</option>',
                                             '<option value="Arial Rounded MT Bold">Arial Rounded MT Bold</option>',
                                             '<option value="Arial Unicode MS">Arial Unicode MS</option>',
                                             '<option value="Baskerville Old Face">Baskerville Old Face</option>',
                                             '<option value="Batang">Batang</option>',
                                             '<option value="BatangChe">BatangChe</option>',
                                             '<option value="Bauhaus 93">Bauhaus 93</option>',
                                             '<option value="Bell MT">Bell MT</option>',
                                             '<option value="Berlin Sans FB">Berlin Sans FB</option>',
                                             '<option value="Berlin Sans FB Demi">Berlin Sans FB Demi</option>',
                                             '<option value="Bernard MT Condensed">Bernard MT Condensed</option>',
                                             '<option value="Blackadder ITC">Blackadder ITC</option>',
                                             '<option value="Bodoni MT">Bodoni MT</option>',
                                             '<option value="Bodoni MT Black">Bodoni MT Black</option>',
                                             '<option value="Bodoni MT Condensed">Bodoni MT Condensed</option>',
                                             '<option value="Bodoni MT Poster Compressed">Bodoni MT Poster Compressed</option>',
                                             '<option value="Book Antiqua">Book Antiqua</option>',
                                             '<option value="Bookman Old Style">Bookman Old Style</option>',
                                             '<option value="Bookshelf Symbol 7">Bookshelf Symbol 7</option>',
                                             '<option value="Bradley Hand ITC">Bradley Hand ITC</option>',
                                             '<option value="Britannic Bold">Britannic Bold</option>',
                                             '<option value="Broadway">Broadway</option>',
                                             '<option value="Brush Script MT">Brush Script MT</option>',
                                             '<option value="Calibri">Calibri</option>',
                                             '<option value="Californian FB">Californian FB</option>',
                                             '<option value="Calisto MT">Calisto MT</option>',
                                             '<option value="Cambria">Cambria</option>',
                                             '<option value="Cambria Math">Cambria Math</option>',
                                             '<option value="Candara">Candara</option>',
                                             '<option value="Castellar">Castellar</option>',
                                             '<option value="Centaur">Centaur</option>',
                                             '<option value="Century">Century</option>',
                                             '<option value="Century Gothic">Century Gothic</option>',
                                             '<option value="Century Schoolbook">Century Schoolbook</option>',
                                             '<option value="Chiller">Chiller</option>',
                                             '<option value="Colonna MT">Colonna MT</option>',
                                             '<option value="Comic Sans MS">Comic Sans MS</option>',
                                             '<option value="Consolas">Consolas</option>',
                                             '<option value="Constantia">Constantia</option>',
                                             '<option value="Cooper Black">Cooper Black</option>',
                                             '<option value="Copperplate Gothic Bold">Copperplate Gothic Bold</option>',
                                             '<option value="Copperplate Gothic Light">Copperplate Gothic Light</option>',
                                             '<option value="Corbel">Corbel</option>',
                                             '<option value="Courier New">Courier New</option>',
                                             '<option value="Curlz MT">Curlz MT</option>',
                                         '</select>',
                                    '</tpl>',
                                '</tpl>',
                        '</tpl>',

                         '<div class="fl font">',
                            '<tpl for="children">',
                                '<tpl switch="id">',
                                    /*'<tpl case="fontType">',
                                        '<tpl if="fontType==\'false\'">',
                                             '<select name="" id="" class="fr selectOP_1" css="{renterTo}" disabled title="字体类型" style="background-color: #7B7C7D;color: #BABABA;border:none;">',
                                                 '<option value="Normal">Normal</option>',
                                                 '<option value="oblique">oblique</option>',
                                                 '<option value="bold">bold</option>',
                                                 '<option value="regular">regular</option>',
                                                 '<option value="bold oblique">bold oblique</option>',
                                             '</select>',
                                        '<tpl else>',
                                             '<select name="" id="" class="fr selectOP_1" css="{renterTo}" title="字体类型" style="background-color: #e3e7e9;border:1px solid #e3e7e9">',
                                                 '<option value="Normal">Normal</option>',
                                                 '<option value="oblique">oblique</option>',
                                                 '<option value="bold">bold</option>',
                                                 '<option value="regular">regular</option>',
                                                 '<option value="bold oblique">bold oblique</option>',
                                             '</select>',
                                        '</tpl>',*/

                             '<tpl case="fontColor">',
                                 '<tpl if="fontColor==\'false\'">',
                                     '<ul class="alignMent fl" style="padding:0;margin:0;">',
                                             '<div class="styleShadow fontColor" style="position:relative;width:44px;height:22px;border:none;margin-right:0;" css="{renterTo}" title="文本颜色">',
                                                '<input class="font_color" style="display:none;">',
                                             '<div class="styleMask"></div>',
                                         '</div>',
                                     '</ul>',
                                 '<tpl else>',
                                     '<ul class="alignMent fl" style="padding:0;margin:0;">',
                                         '<div class="styleShadow fontColor" style="position:relative;width:44px;height:22px;border:none;margin-right:0;" css="{renterTo}" title="文本颜色">',
                                            '<input class="font_color" style="display:none;">',
                                         '</div>',
                                     '</ul>',
                                 '</tpl>',

                                 '<tpl case="fontShadow">',
                                     '<tpl if="fontShadow==\'false\'">',
                                         '<ul class="alignMent fl" style="padding:0;margin:0;">',
                                             '<div class="styleShadow fonShadow" style="padding:4px 8px;margin-right:0px;width: 44px;margin-left: 5px;float:left;border:none;" css="{renterTo}" title="文字阴影">',
                                                 '<span class="icon2" style="margin: 3px -1px 0 0 !important;"></span>',
                                                 '<span class="iconStyle style_FontShadow" style="margin:-14px 14px 0 0;width:12px;height:12px;"></span>',
                                                 '<div class="shadowInner pubHideBox" style="height:100px;right: -60px;">',
                                                     '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                     '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetTextX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetTextY" css="{renterTo}" disabled></div>',
                                                     '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurText" css="{renterTo}" disabled> 颜色 <div class="textShadowColor"><input class="textShadow" css="{renterTo}" readonly style="display:none;"><div class="styleMask" style="display: block;"></div></div>',
                                                 '</div>',
                                             '</div>',
                                             '<div class="styleMask"></div>',
                                         '</ul>',
                                     '<tpl else>',
                                         '<ul class="alignMent fl" style="padding:0;margin:0;">',
                                             '<div class="styleShadow fonShadow" style="padding:4px 8px;margin-right:0px;width: 44px;margin-left: 5px;float:left;" css="{renterTo}" title="文字阴影">',
                                                '<span class="icon2" style="margin: 3px -1px 0 0 !important;"></span>',
                                                '<span class="iconStyle style_FontShadow" style="margin:-14px 14px 0 0;width:12px;height:12px;"></span>',
                                                 '<div class="shadowInner pubHideBox" style="height:100px;right: -60px;">',
                                                    '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                    '<div class="shadowMaskFather">偏移量: x <input type="text" class="offsetTextX" css="{renterTo}" disabled> y <input type="text" class="offsetTextY" css="{renterTo}" disabled></div>',
                                                    '<div class="shadowMaskFather">模糊: <input type="text" class="blurText" css="{renterTo}" disabled> 颜色 <div class="textShadowColor"><input class="textShadow" css="{renterTo}" style="display:none;"><div class="styleMask" style="display: block;"></div></div>',
                                                 '</div>',
                                             '</div>',
                                         '</ul>',
                                     '</tpl>',

                                    '<tpl case="fontSize">',
                                        '<tpl if="fontSize==\'false\'">',
                                             '<select class="selectFontSize fr" css="{renterTo}" disabled title="字体尺寸" style="background-color: #7B7C7D;color: #BABABA;border:none;">',
                                                 '<option value="" style="display: none" selected></option>',
                                                 '<option value="12">12</option>',
                                                 '<option value="13">13</option>',
                                                 '<option value="14">14</option>',
                                                 '<option value="15">15</option>',
                                                 '<option value="16">16</option>',
                                                 '<option value="18">18</option>',
                                                 '<option value="20">20</option>',
                                                 '<option value="28">28</option>',
                                                 '<option value="36">36</option>',
                                                 '<option value="48">48</option>',
                                                 '<option value="72">72</option>',
                                             '</select>',
                                             '<input type="text" class="edtiorFontSize" css="{renterTo}" value="12">',
                                        '<tpl else>',
                                             '<select class="selectFontSize fr" css="{renterTo}" title="字体尺寸" style="background-color: #e3e7e9;border:1px solid #e3e7e9">',
                                                 '<option value="" style="display: none" selected></option>',
                                                 '<option value="12">12</option>',
                                                 '<option value="13">13</option>',
                                                 '<option value="14">14</option>',
                                                 '<option value="15">15</option>',
                                                 '<option value="16">16</option>',
                                                 '<option value="18">18</option>',
                                                 '<option value="20">20</option>',
                                                 '<option value="28">28</option>',
                                                 '<option value="36">36</option>',
                                                 '<option value="48">48</option>',
                                                 '<option value="72">72</option>',
                                             '</select>',
                                             '<input type="text" class="edtiorFontSize" css="{renterTo}" value="12">',
                                        '</tpl>',

                                    '</tpl>',
                                '</tpl>',
                         '</div>',
                        /* '<div class="fl font">',
                            '<div class="fl fontStyles">',
                            '<tpl for="children">',
                                '<tpl switch="id">',
                                    '<tpl case="fontColor">',
                                        '<tpl if="fontColor==\'false\'">',
                                             '<ul class="alignMent fr" style="padding:0;margin:0;">',
                                                 '<div class="styleShadow fontColor" style="position:relative;width:44px;height:22px;border:none;margin-right:0;" css="{renterTo}" title="文本颜色">',
                                                    '<input class="font_color" style="display:none;">',
                                                    '<div class="styleMask"></div>',
                                                 '</div>',
                                             '</ul>',
                                        '<tpl else>',
                                             '<ul class="alignMent fr" style="padding:0;margin:0;">',
                                                 '<div class="styleShadow fontColor" style="position:relative;width:44px;height:22px;border:none;margin-right:0;" css="{renterTo}" title="文本颜色">',
                                                    '<input class="font_color" style="display:none;">',
                                                 '</div>',
                                             '</ul>',
                                        '</tpl>',
                                    '<tpl case="fontShadow">',
                                        '<tpl if="fontShadow==\'false\'">',
                                             '<ul class="alignMent fr" style="padding:0;margin:0;">',
                                                 '<div class="styleShadow fonShadow" style="padding:4px 8px;margin-right:0px;width: 44px;margin-left: 5px;float:left;border:none;" css="{renterTo}" title="文字阴影">',
                                                    '<span class="icon2" style="margin: 3px -1px 0 0 !important;"></span>',
                                                    '<span class="iconStyle style_FontShadow" style="margin:-14px 14px 0 0;width:12px;height:12px;"></span>',
                                                     '<div class="shadowInner pubHideBox" style="height:100px;right: -60px;">',
                                                        '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                        '<div class="shadowMaskFather">偏移量: x <input type="text" class="readonlyIput offsetTextX" css="{renterTo}" disabled> y <input type="text" class="readonlyIput offsetTextY" css="{renterTo}" disabled></div>',
                                                        '<div class="shadowMaskFather">模糊: <input type="text" class="readonlyIput blurText" css="{renterTo}" disabled> 颜色 <div class="textShadowColor"><input class="textShadow" css="{renterTo}" readonly style="display:none;"><div class="styleMask" style="display: block;"></div></div>',
                                                     '</div>',
                                                 '</div>',
                                                 '<div class="styleMask"></div>',
                                             '</ul>',
                                        '<tpl else>',
                                             '<ul class="alignMent fr" style="padding:0;margin:0;">',
                                                 '<div class="styleShadow fonShadow" style="padding:4px 8px;margin-right:0px;width: 44px;margin-left: 5px;float:left;" css="{renterTo}" title="文字阴影">',
                                                    '<span class="icon2" style="margin: 3px -1px 0 0 !important;"></span>',
                                                    '<span class="iconStyle style_FontShadow" style="margin:-14px 14px 0 0;width:12px;height:12px;"></span>',
                                                     '<div class="shadowInner pubHideBox" style="height:100px;right: -60px;">',
                                                        '<input type="checkbox" class="inputVertical" css="{renterTo}"> 阴影',
                                                        '<div class="shadowMaskFather">偏移量: x <input type="text" class="offsetTextX" css="{renterTo}" disabled> y <input type="text" class="offsetTextY" css="{renterTo}" disabled></div>',
                                                        '<div class="shadowMaskFather">模糊: <input type="text" class="blurText" css="{renterTo}" disabled> 颜色 <div class="textShadowColor"><input class="textShadow" css="{renterTo}" style="display:none;"><div class="styleMask" style="display: block;"></div></div>',
                                                     '</div>',
                                                 '</div>',
                                             '</ul>',
                                        '</tpl>',
                                    '</tpl>',
                                '</tpl>',
                            '</div>',
                         '</div>',*/

                         '<div class="fl font">',
                            '<div class="fl fontStyles">',
                                '<ul class="alignMent fl" style="padding:0;margin:0;width: 100%;">',
                                    '<tpl for="children">',
                                        '<tpl switch="id">',
                                            '<tpl case="fontBold">',
                                                '<tpl if="fontBold==\'false\'">',
                                                     '<div class="styleShadow fontStyleIcon fontBold" css="{renterTo}" title="粗体" style="margin-right:5px;border-radius: 2px;border:none;">',
                                                        '<span class="iconStyle style_FontBold small-Style"></span>',
                                                        '<div class="styleMask"></div>',
                                                     '</div>',
                                                '<tpl else>',
                                                     '<div class="styleShadow fontStyleIcon fontBold" css="{renterTo}" title="粗体" style="margin-right:5px;border-radius: 2px;">',
                                                        '<span class="iconStyle style_FontBold small-Style"></span>',
                                                     '</div>',
                                                '</tpl>',
                                            '<tpl case="fontItalics">',
                                                '<tpl if="fontItalics==\'false\'">',
                                                     '<div class="styleShadow fontStyleIcon fontOblique" css="{renterTo}" title="斜体" style="margin-right:5px;border-radius:2px;border:none;">',
                                                        '<span class="iconStyle style_FontItalics small-Style"></span>',
                                                        '<div class="styleMask"></div>',
                                                     '</div>',
                                                '<tpl else>',
                                                     '<div class="styleShadow fontStyleIcon fontOblique" css="{renterTo}" title="斜体" style="margin-right:5px;border-radius: 2px;">',
                                                        '<span class="iconStyle style_FontItalics small-Style"></span>',
                                                     '</div>',
                                                '</tpl>',
                                                '<tpl case="fontUnderline">',
                                                    '<tpl if="fontUnderline==\'false\'">',
                                                         '<div class="styleShadow fontStyleIcon underline" css="{renterTo}" title="下划线" style="border-radius:2px;border:none;">',
                                                            '<span class="iconStyle style_Underline small-Style"></span>',
                                                            '<div class="styleMask"></div>',
                                                         '</div>',
                                                    '<tpl else>',
                                                         '<div class="styleShadow fontStyleIcon underline" css="{renterTo}" title="下划线" style="border-radius: 2px;">',
                                                            '<span class="iconStyle style_Underline small-Style"></span>',
                                                         '</div>',
                                                    '</tpl>',
                                            '</tpl>',
                                        '</tpl>',
                                '</ul>',
                            '</div>',
                         '</div>',


                    '</div>',
                '</div>',
             '</tpl>',

            '<tpl if="id==\'lineSpacing\' && display==\'true\'">',
                '<div class="styleLine" title="行间距">',
                    '<span class="fl pubLeft">行间距</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                            '<tpl if="id==\'lineSpacingValue\' && lineSpacingValue==\'false\'">',
                                '<select name="" id="" class="lineSpace fl" disabled css="{renterTo}" style="background-color: #7B7C7D;color: #BABABA;border:none;">',
                                    '<option value="" style="display: none"></option>',
                                    '<option value="--">--</option>',
                                    '<option value="6">6</option>',
                                    '<option value="7">7</option>',
                                    '<option value="8">8</option>',
                                    '<option value="9">9</option>',
                                    '<option value="10">10</option>',
                                    '<option value="11">11</option>',
                                    '<option value="12">12</option>',
                                    '<option value="13">13</option>',
                                    '<option value="14">14</option>',
                                    '<option value="16">16</option>',
                                    '<option value="18">18</option>',
                                    '<option value="20">20</option>',
                                    '<option value="28">28</option>',
                                    '<option value="36">36</option>',
                                    '<option value="48">48</option>',
                                    '<option value="72">72</option>',
                                '</select>',
                                '<input type="text" class="edtiorSelect" css="{renterTo}" value="--">',
                            '<tpl else>',
                                '<select name="" id="" class="lineSpace fl" css="{renterTo}" style="background-color: #e3e7e9;border:1px solid #e3e7e9">',
                                    '<option value="" style="display: none"></option>',
                                    '<option value="--">--</option>',
                                    '<option value="6">6</option>',
                                    '<option value="7">7</option>',
                                    '<option value="8">8</option>',
                                    '<option value="9">9</option>',
                                    '<option value="10">10</option>',
                                    '<option value="11">11</option>',
                                    '<option value="12">12</option>',
                                    '<option value="13">13</option>',
                                    '<option value="14">14</option>',
                                    '<option value="16">16</option>',
                                    '<option value="18">18</option>',
                                    '<option value="20">20</option>',
                                    '<option value="28">28</option>',
                                    '<option value="36">36</option>',
                                    '<option value="48">48</option>',
                                    '<option value="72">72</option>',
                                '</select>',
                                '<input type="text" class="edtiorSelect" css="{renterTo}" value="--">',
                            '</tpl>',
                        '</tpl>',
                    '</div>',
                '</div>',
            '</tpl>',

            '<tpl if="id==\'align\' && display==\'true\'">',
                '<div class="styleLine">',
                    '<span class="fl pubLeft">对齐</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                            '<tpl switch="id">',
                                '<tpl case="textAlign">',
                                     '<tpl if="id==\'textAlign\' && textAlign==\'false\'">',
                                        '<ul class="alignMent alignMentAlign fr" style="margin-right:8px;padding-left:0;width:66px;position:relative;border:none;">',
                                            '<div class="styleShadow fontStyleIcon alignLeft" title="左侧对齐" css="{renterTo}">',
                                                '<span class="iconStyle  style_AlignLeft small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignCenter" title="水平居中" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignCenter small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignRight" title="右侧对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignRight small-Style"></span>',
                                            '</div>',
                                            '<div class="styleMask"></div>',
                                        '</ul>',
                                     '<tpl else>',
                                        '<ul class="alignMent alignMentAlign fr" style="margin-right:8px;padding-left:0;width:66px;position:relative;">',
                                            '<div class="styleShadow fontStyleIcon alignLeft" title="左侧对齐" css="{renterTo}">',
                                                '<span class="iconStyle  style_AlignLeft small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignCenter" title="水平居中" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignCenter small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignRight" title="右侧对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignRight small-Style"></span>',
                                            '</div>',
                                        '</ul>',
                                    '</tpl>',
                                '<tpl case="vertical">',
                                    '<tpl if="id==\'vertical\' && vertical==\'false\'">',
                                        '<ul class="alignMent alignVertical fr" style="margin:0;width:66px;position:relative;border:none;">',
                                            '<div class="styleShadow fontStyleIcon alignTop" title="顶部对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignTop small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon verticalCenter" title="垂直居中" css="{renterTo}">',
                                                '<span class="iconStyle style_VerticalCenter small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignBottom" title="底部对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignBottom small-Style"></span>',
                                            '</div>',
                                            '<div class="styleMask"></div>',
                                        '</ul>',
                                    '<tpl else>',
                                        '<ul class="alignMent alignVertical fr" style="margin:0;width:66px;">',
                                            '<div class="styleShadow fontStyleIcon alignTop" title="顶部对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignTop small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon verticalCenter" title="垂直居中" css="{renterTo}">',
                                                '<span class="iconStyle style_VerticalCenter small-Style"></span>',
                                            '</div>',
                                            '<div class="styleShadow fontStyleIcon alignBottom" title="底部对齐" css="{renterTo}">',
                                                '<span class="iconStyle style_AlignBottom small-Style"></span>',
                                            '</div>',
                                        '</ul>',
                                    '</tpl>',
                            '</tpl>',
                        '</tpl>',
                    '</div>',
                '</div>',
            '</tpl>',

            '<tpl if="id==\'padding\' && display==\'true\'">',
                '<div class="styleLine">',
                    '<span class="fl pubLeft">填充</span>',
                    '<div class="fr pubRight">',
                        '<tpl for="children">',
                             '<tpl if="id==\'paddingAll\' && paddingAll==\'false\'">',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingLeft" title="Left padding"  css="{renterTo}" disabled style="background-color: #7B7C7D;"><br>',
                                         '<span>左</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingTop" title="Top padding" css="{renterTo}" disabled style="background-color: #7B7C7D;"><br>',
                                         '<span>上</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingRight" title="Right padding" css="{renterTo}" disabled style="background-color: #7B7C7D;"><br>',
                                         '<span>右</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox" style="margin: 0;">',
                                     '<div >',
                                        '<input type="text" value="2" class="paddingBottom" title="Bottom padding" css="{renterTo}" disabled style="background-color: #7B7C7D;"><br>',
                                        '<span>下</span>',
                                     '</div>',
                                 '</div>',
                             '<tpl else>',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingLeft" title="Left padding"  css="{renterTo}"><br>',
                                         '<span>左</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingTop" title="Top padding" css="{renterTo}"><br>',
                                         '<span>上</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox">',
                                     '<div>',
                                         '<input type="text" value="2" class="paddingRight" title="Right padding" css="{renterTo}"><br>',
                                         '<span>右</span>',
                                     '</div>',
                                 '</div>',
                                 '<div class="fl paddingBox" style="margin: 0;">',
                                     '<div>',
                                        '<input type="text" value="2" class="paddingBottom" title="Bottom padding" css="{renterTo}"><br>',
                                        '<span>下</span>',
                                     '</div>',
                                 '</div>',
                             '</tpl>',
                        '</tpl>',
                    '</div>',
                '</div>',
            '</tpl>',
        '</tpl>',
        '</div>'
    ),
    /** 属性空白页面 */
    PROPERTY_DEFAULT:
        new Ext.XTemplate(
            '<div class="pageBoxContProperty">',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">类型</span>',
                    '<div class="fr pubRight">',
                        '<span style="display: inline-block;height:21px;line-height:21px;color:#000;">DDS</span>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft" style="font-size: 12px;">标题</span>',
                    '<div class="fr pubRight">',
                        '<input type="text" class="pageTitle" id="pageTitle" value="dds" style="width: 142px;text-align: left;font-size: 12px;padding-left: 4px;">',
                    '</div>',
                '</div>',
                /*'<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">主题</span>',
                    '<div class="fr pubRight">',
                        '<select class="fl derma"  id="derma" title="Cosui主题" style="background-color: #e3e7e9;border:1px solid #e3e7e9;width:142px !important;">',
                            '<option value="default">默认</option>',
                            '<option value="bootstrap">Bootstrap</option>',
                            '<option value="gray">Gray</option>',
                            '<option value="black">Black</option>',
                            '<option value="material">Material</option>',
                            '<option value="metro">Metro</option>',
                        '</select>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">ECharts</span>',
                    '<div class="fr pubRight">',
                        '<select class="fl derma" id="echartsderma" title="ECharts主题" style="background-color: #e3e7e9;border:1px solid #e3e7e9;width:142px !important;">',
                            '<option value="default">默认</option>',
                            '<option value="dark">Dark</option>',
                            '<option value="infographic">Infographic</option>',
                            '<option value="Macarons">Macarons</option>',
                            '<option value="Roma">Roma</option>',
                            '<option value="shine">Shine</option>',
                            '<option value="vintage">Vintage</option>',
                        '</select>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">事件</span>',
                    '<div class="fr pubRight">',
                        '<select name="" id="pageEven" class="fr selectOP_1" title="事件" style="background-color: #e3e7e9;border:1px solid #e3e7e9;width:142px !important;">',
                            '<option value="Normal">更多事件>></option>',
                            '<option value="onLoad">页面加载完成时</option>',
                        '</select>',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft">自适应</span>',
                    '<div class="fr pubRight">',
                        '<select name="" id="pageAdaption" class="fr selectOP_1"  title="自适应" style="background-color: #e3e7e9;border:1px solid #e3e7e9;width:142px !important;">',
                            '<option value="Normal">是</option>',
                            '<option value="oblique">否</option>',
                        '</select>',
                    '</div>',
                '</div>',*/
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft" style="font-size: 12px;">Key</span>',
                    '<div class="fr pubRight">',
                        '<input type="text" class="pageTitle" id="PageKey" style="width: 142px;text-align: left;font-size: 12px;padding-left: 4px;">',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft" style="font-size: 12px;">Name</span>',
                    '<div class="fr pubRight">',
                        '<input type="text" class="pageTitle" id="PageName" style="width: 142px;text-align: left;font-size: 12px;padding-left: 4px;">',
                    '</div>',
                '</div>',
                '<div class="styleLine styleFont">',
                    '<span class="fl pubLeft" style="font-size: 12px;">Description</span>',
                    '<div class="fr pubRight">',
                        '<textarea class="pageTitle" id="PageDescription" style="width: 142px;text-align: left;font-size: 12px;padding-left: 4px;"></textarea>',
                    '</div>',
                '</div>',
            '</div>'
        ),
});

